input {
    file {
        path => "/app/logs/trade-journal-service-logs/trade-journal-service.json"
        start_position => "beginning"
        sincedb_path => "/dev/null"
        codec => json
		tags => ["open-trade-journal-service"]
    }
	
	file {
       path => "/app/logs/trade-journal-gateway-logs/trade-journal-gateway.json"
       start_position => "beginning"
       sincedb_path => "/dev/null"
       codec => json
       tags => ["open-trade-journal-gateway"]
    }
	file {
       path => "/app/logs/trade-journal-front-logs/*.log"
       start_position => "beginning"
       sincedb_path => "/dev/null"
       codec => json
       tags => ["open-trade-journal-front"]
    }
  
}

output {
    elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "trade-journal-%{+YYYY.MM.dd}"
    }

    stdout {
        codec => rubydebug
    }
}